### ISSUE TITLE
Awkward space when the option "No Package Manager" is selected

### ISSUE THREAD

**Issue by GaryHilares** [beyondcode/banners#13]
## Description
When the option "No Package Manager" is selected an awkward space appears between the first quotation mark and the description given by the user.

## Expected behaviour
That space should not appear.

## Screenshot
![issue screenshot 1](https://user-images.githubusercontent.com/46727048/118297404-b25c6280-b4a3-11eb-877c-2a64715059ba.png)

**Comment by marcreichel** [comment]
I've created PR #12 on March 23rd which fixes this behavior. Sadly it was not approved and merged since then ...

So maybe another friendly reminder to @mpociot to approve the PR may help?!

**Comment by marcreichel** [comment]
@mechelon Why did you close this issue, but the referenced PR is still open? 🤔
